server:
  port: 9192
spring:
  application:
    name: meetup
  security:
    oauth2:
      resource:
        token-info-uri: https://womakerscode-auth-api.azurewebsites.net/oauth/check_token
      client:
        client-id: web
        client-secret: pin
  datasource:
    url: jdbc:mysql://womakersmeetupdb.mysql.database.azure.com:3306/meetupdb?serverTimezone=UTC
    username: spring@womakersmeetupdb
    password: womakers2022!
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: DEBUG

