server:
  port: 9192
spring:
  rabbitmq:
    addresses: amqps://localhost:8089
  application:
    name: meetup
  security:
    oauth2:
      resource:
        token-info-uri: http://localhost:8085
      client:
        client-id: web
        client-secret: pin
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    initialization-mode: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: DEBUG

